### PR TITLE
fix: typos and inconsistencies in metric descriptions

### LINKED ISSUE #80: There are typos in certain metric descriptions

### PR DESCRIPTION
**Pull request by KevBelisle**
Should fix #80 

Signed-off-by: Kevin Belisle <kev.belisle@gmail.com>

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hi @KevBelisle,

thanks for the contribution! looks very good! 

Can you update the descriptions in the example in the README.md file too?

So we keep docs always consistent with the code.

If done, I can merge this PR. Cheers!

**Comment by KevBelisle** [comment]
@dirien I updated the readme! A fun 15 min of find, copy, paste, repeat!

**Comment by KevBelisle** [comment]
I also noticed some typos in the metric names, eg: `animals_breded_total` should be `animals_bred_total`

Since that would be breaking change, I didn't include it in this PR.

**Comment by dirien** [comment]
hi @KevBelisle,

I can imagine this :( Just one question: Did you commit the readme? I miss it in the PR?

For the breaking changes, we can create a different PR and mark it in the Release Notes.

**Comment by KevBelisle** [comment]
@dirien Whoops, should be good now.

**Review by dirien — CHANGES_REQUESTED** [review]
@KevBelisle, looks very good now! 

Would merge it, when you run 

```
git commit --amend -s    
git push origin --force
```

on your current branch!

**Review by dirien — APPROVED** [review]
hi @KevBelisle, perfect! thanks for the contribution!

**Pull request merged**
