### PR TITLE
fix: minecraft_play_time_ticks_total

### LINKED ISSUE #79: The "minecraft_play_time_ticks_total" metric is always 0

### PR DESCRIPTION
**Pull request by KevBelisle**
This should fix #79 

Signed-off-by: Kevin Belisle <kev.belisle@gmail.com>

### CODE REVIEW

**Review by dirien — APPROVED** [review]
Thanks @KevBelisle, for the fix! I tested it and now i see the time in ticks!

**Review by dirien — CHANGES_REQUESTED** [review]
@KevBelisle can you resolve the conflict and change the description in the README.md too please?

Then I can merge the PR and create a new release. Thanks!

**Comment by KevBelisle** [comment]
> @KevBelisle can you resolve the conflict and change the description in the README.md too please?
> 
> Then I can merge the PR and create a new release. Thanks!

Done!

The description in the README.md should already be ok.

**Comment by dirien** [comment]
Thanks @KevBelisle! Its merged!

**Pull request merged**
